### ISSUE TITLE
AAC resampling from 48kHz to 44.1kHz is a little bit distorted

### ISSUE THREAD

**Issue by Vouk** [Vouk/voukoder#14]
rounding errors?

**Comment by schauerland** [comment]
maybe let ffmpeg resample?
-ar 44100 to 44.1
-ar 44800 to 48 and so on

ffmpeg -i file1.wav -ar 44100 file1-enc.wav

**Comment by Vouk** [comment]
This happens already using the filterGraph.

**Comment by Vouk** [comment]
Issue has been fixed!
