### ISSUE TITLE
Get "Faststart" working

### ISSUE THREAD

**Issue by Vouk** [Vouk/voukoder#17]
Add parameters to "mp4" and "mov" multiplexer to set flag of avformat_write_header() options:
av_dict_set(&options, "movflags", "faststart", 0);  //+faststart?

The muxer currently has the problem to reopen file again after writing it.
Need to check this.

**Comment by schauerland** [comment]
there are multiple movflags that can be set.
faststart will set to only faststart and +faststart will add to movflags

so +faststart will be saver.

**Comment by schauerland** [comment]
https://ffmpeg.org/ffmpeg-formats.html#Options-8

**Comment by Vouk** [comment]
Enabled by default in 0.6
