### ISSUE TITLE
Filesize calculation is rubbish

### ISSUE THREAD

**Issue by Vouk** [Vouk/voukoder#20]
Is known. But what can be show when using qp or crf?

**Comment by Vouk** [comment]
Make it work at least for scenarios with a fixed bitrate.

**Comment by schauerland** [comment]
qp/crf are quality based encodings, so you can't predict file size.
it's depending on frame complexity and the encoder will provide as much bitrate as possible to reach the quality factor.

**Comment by schauerland** [comment]
so qp/crf are mostly interesting when filesize, but quality matters.

**Comment by Vouk** [comment]
I have set the estimated filesize to 0 as it is impossible to calculate. The estimate filesize is not visible anymore in the UI (at least in CS6).
