### ISSUE TITLE
Encoder crash in Media Encoder 2018 (Debug)

### ISSUE THREAD

**Issue by schauerland** [Vouk/voukoder#26]
After a few minutes of encoding I'm now getting this crash message.
current checkout.
![err](https://user-images.githubusercontent.com/34268502/34096311-293f1ada-e3d5-11e7-9d3c-04b4197befb9.PNG)

**Comment by Vouk** [comment]
Provide more details. pls:
- What input format?
- What output format?
- Copy debug console output
- Steps to reproduce

**Comment by schauerland** [comment]
default timeline i think it's RGB?
only used h264 yuv420 bt.702 as input files
output x264 slower crf 20 minkeyint=60 maxkeyint=600 yuv420 bt.702 60fps 1080p
this was just a debug build copied to the plugin folder - no console or stack as far as it does not write to a file?

**Comment by schauerland** [comment]
wil re-check if only happens in media encoder but also in premiere itself.
but should work same.

**Comment by Vouk** [comment]
You could start premiere in the debugger. You will get a console log, and the exception will stop the execution and show you a stacktrace.

**Comment by Vouk** [comment]
This should be fixed in the latest master.
