### ISSUE TITLE
Hevc lossless is not real lossless

### ISSUE THREAD

**Issue by qo4on** [Vouk/voukoder#29]
It works on gtx 1060.
The source is yuv 4:2:0. In PP I see the same colors, but there is an outline at the bright colored edges in layer difference mode.
![test](https://user-images.githubusercontent.com/35609308/35166359-6fd88c1c-fd73-11e7-9e9e-80aaa54430b9.png)
 - Why there is no spatial AQ and 2 pass vbr?
 - Buffer size 0 means automatic? Which value do you suggest?
 - How does Maximum render quality affect to the encoding process?

**Comment by schauerland** [comment]
hey,
We will add missing features step by step. Please let us know if you miss something else.
But we're only able to add features as part of ffmpeg.

To see all options we can set please look at ffmpeg -h encoder=hevc_nvenc

Yes Buffer Size 0 means automatic. I's limited by NVIDIA to 288 Mbit.

Render quality will increase render time no matter what codec you are unsing.

the frame will be rendered first by Adobe and the pushed to the encoder

**Comment by qo4on** [comment]
Hi! Thank you for this great plugin!
Why don't you comment why lossless hevc nvenc is not lossless?

**Comment by schauerland** [comment]
I'll look into that.

I'm not the main developer. I do testing and support/research.

Is the resolution of your footage and output the same?

**Comment by Vouk** [comment]
I guess all questions were related to nvenc h.264? 

1.) Encoding can be lossless, rendering not necessarily. Premiere might do internal pixel- / color format conversion, that is not in our control. But there are some special pixel formats like UYVY that gets unmodified passthrough. To archieve entirely lossless rendering and encoding use an UYVY 4:2:2 clip and export it as yuv 4:2:2 with x265 lossless. Any applied effects or transitions could cause artifacts due to pixel- / color format conversion (some only support rgb).

2.) Please supply a list of additional parameters you are interested in per encoder. We'll look into 2pass.

3.) According to the SDK documentation the "render quality" setting allows the use of more precise internal algorithms. The plug-in itself does not make use of this setting anymore.

**Comment by qo4on** [comment]
Probably the difference appeared because of the Premiere Pro h265 lossless decoding bug.
- Add ffmpeg command line to UI of your encoder which could override all settings.
- hevc tier high always generates error in lossless mode.
- I think it would be better to hide non-working options depending on the preset. I don't think that Strategy and LookAhead options make any difference in lossless mode.

**Comment by Vouk** [comment]
- ffmpeg command line is not available as ffmpeg is beeing used as a static library, not as an executable
- Put the plugin in i.e. C:\Program Files\Adobe\Common\Plug-ins\CS6\MediaCore\ and it should work with after effects do (change version if neccessary)

**Comment by qo4on** [comment]
- After Effects 2018 does not see the plugin in C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore
I think it's more important to ensure that encoder uses latest NVIDIA and Adobe SDK, makes no visual artifacts, no duplicated/lost frames, provides color accuracy and high speed than additional parameters. If I find any other issues I will let you know.

**Comment by Vouk** [comment]
According to the latest SDKs documentation it should be correct, but i don't have After Effects to test this. Sorry.

The SDK is for CS6 (the oldest supported version). The SDK consists only of header files defining the API. The actual functionality is within the host application. So it uses the functionality of the executing premiere version. All other sources are up to and are built from the master branch of their repositories.

**Comment by qo4on** [comment]
I think it may work through the dynamic link from PP. But from AE it's not available. ![1](https://user-images.githubusercontent.com/35609308/35280093-e8cccf98-0070-11e8-81a0-c99de7d217ed.png)

**Comment by Vouk** [comment]
Can you queue After Effect projects in Adobe Media Encoder? It should work there.

**Comment by qo4on** [comment]
It will work in AME, I know. But I prefer not using it. I will work in PP, its export does better. AE is a good way to evolve your plugin but not necessary.

**Comment by Vouk** [comment]
All encoder options have been added. Closing this.
