### ISSUE TITLE
Only able to render with a framerate of 60FPS

### ISSUE THREAD

**Issue by Trivernis** [Vouk/voukoder#36]
When I use the plugin with Adobe Media Encoder it does not render the video unless I choose a framerate of 60FPS. Otherwise the rendering is finished with a warning and the file is broken with a size of 1 KB. 
[error.txt](https://github.com/Vouk/voukoder/files/1740961/error.txt)

**Comment by Vouk** [comment]
Did you update from a previous voukoder version? Did you try a fresh, new project?

I will let voukoder genereate its own logfile in the next version.

**Comment by Vouk** [comment]
Should be fixed with 0.6.4 ... can you confirm?
