### ISSUE TITLE
Export with full color range does not work

### ISSUE THREAD

**Issue by Clockiy** [Vouk/voukoder#37]
Hey,
the Option "Use Full Color Range" is inverted I think. When I dont tick it, it seems to output the full RGB Spectrum, but when I tick it, it does not output the full spectrum.

**Comment by Vouk** [comment]
Thanks for reporting this. I will check it.

**Comment by Vouk** [comment]
Checked it again:
- If check it is using the *_FullRange pixel formats in premiere
- Setting the VUI flags is also correct
- MPC-HC plays both exported files perfectly

Looks good so far. Maybe you can show example screenshots? Please use test color-bars for this only.

**Comment by Clockiy** [comment]
Hey, full color range is still inverted. Here are 3 Videos: https://drive.google.com/open?id=1H_IVofLihYmxkPLd7i5z4P-A49JvKJEm
enc_h264_FR = Default Adobe encoder with Full Color Ranged enabled (no problems)
enc_vouk_FCR = Use Full color Range enabled (Color Range is only Limited)
enc_vouk_woFCR = Use Full color Range disabled (Color Range of exported Video IS full)

At around 5-10 seconds is a testscreen where you can check that out

**Comment by Vouk** [comment]
There is a problem, yes. Premiere does not convert the color range itself.

When requesting the pixel data in "PrPixelFormat_YUV_420_MPEG4_FRAME_PICTURE_PLANAR_8u_709_FullRange" it delivers "#101010"  as black.

**Comment by Clockiy** [comment]
And why does it have no problem using the full range of colors when rendering with the default h264 encoder? Are you able to fix that?

**Comment by Vouk** [comment]
I am looking into this.

**Comment by Vouk** [comment]
Removing this option as this seems to only make sense with RGB and we want to handle YUV only.

**Comment by Clockiy** [comment]
Hey. Closing this issue then is Alright.
But interestingly enough was, when i was selecting the "render at maximum depth" in the default Adobe Encoder, it only then used the full color range.
But yours is working without that option at full range anyway.
