### ISSUE TITLE
FPS & Audio Bitrate doesn't equal Input

### ISSUE THREAD

**Issue by Clockiy** [Vouk/voukoder#38]
Hey there,
when I select the 60 FPS option in the NVENC Encoder Setting, and the 256kbit/s Audio option, it is not proper. The Encoded file shows 60.02 FPS and the Audio Bitrate is between 253kbit/ up to 260kbit/s:

![vouk3](https://user-images.githubusercontent.com/1611400/36867271-efa9deaa-1d94-11e8-9b39-7cb78278b399.JPEG)

The Default H264 encoder is doing a good job with the following like that - you have an Advanced Option under the Audio Tab where you can select the priority: Either [Bitrate] or [Samplerate]:

![vouk2](https://user-images.githubusercontent.com/1611400/36867270-ef903572-1d94-11e8-9f0d-88a5795b9486.JPG)

And maybe add a more understable Audio Setting where you can select the Audioquality: Low/Medium/High - as in the default Audio Settings of H264 in AAC format (it would be easier for the default user):

![vouk1](https://user-images.githubusercontent.com/1611400/36867426-5cfeefea-1d95-11e8-9b33-6e25b0e56887.JPG)

Otherwise great job!
Schönen Abend ;D

**Comment by Vouk** [comment]
Ich schaue mir das später an, klingt aber erst einmal nicht nach einem Fehler! Danke. :)

**Comment by Clockiy** [comment]
Alles klar. Weißt du, woran das den liegen könnte? Also das der nicht die exakte Bitrate und FPS encodiert?

**Comment by Vouk** [comment]
Kann es sein das du MKV als Container benutzt? MKV speichert diese Information nicht im Container und der Decoder muss sie aus der Länge eines Frames interpolieren, da kommen dann solche krummen Zahlen heraus.

**Comment by Clockiy** [comment]
Nein, alles im .mp4 container. Sowohl die RAW Datei mit Shadowplay NVENC. aufgenommen, als auch encodiert mit NVENC. Kann es aber sein, dass dein Plugin vielleicht nicht mit RAW Dateien, die eine variable Framerate verfügen, korrekt klar kommt?

**Comment by Vouk** [comment]
Es gab noch ein Problem mit VFR im aktuellen Release. Er sollte nun aber ab 0.6.4 die nächstliegende Framerate automatisch selektieren. Es gibt aber keine Garantie das er genau auch diese Frames genau so zeitlich schreibt. Wenn Premiere Frames abweichend von dieser timebase liefert, kann die Framerate tatsächlich leicht abweichen. Das liegt auch daran wie der Dekoder dann die fps ermittelt. Entweder der fixe Wert aus dem Container, oder anhand der tatsächlichen Frame-Zeiten.

Ich würde erstmal sagen das das so in Ordnung ist. Kannst du dabei irgendwelche Probleme feststellen?

**Comment by Vouk** [comment]
Sind 2 verschiedene Dinge.
- AAC wird in dem Fall mit variabler bitrate kodiert -> Ok!
- Die Sache mit den FPS braucht ein wenig Behandlung im Code. Siehe auch: https://www.voukoder.org/forum/thread/10-voukoder-creates-variable-framerate-instead-of-constant/?postID=54

**Comment by Clockiy** [comment]
Hey, danke für die ausführlichen Antworten.

Bzg AAC: Bei dem normalen H264 Encoder benutzt Adobe eine konstante Bitrate. Ist es möglich, dass du dieses Feature auch einbaust? Also das man auswählen kann, ob die eingegebene Audio Bitrate konstant geschrieben werden soll? Wie bereits ganz oben bei meinem Post erwähnt (siehe Bild) kann man beim Standard Encoder die Audio Priorität wählen, ob Adobe auf die Bitrate oder Samplerate acht geben soll, sodass die eingegebene Bitrate zu 100% beachtet wird.

Bzg FPS: Beim Encoden mit dem Standard H264 Setting von Adobe konvertiert Premiere die VFR Aufnahme von ShadowPlay in konstante Frames, sodass die exportierte Datei exakt z.B. 60 FPS hat. Dies ist aber auch erst seit dem neuesten Update problemlos machbar. Dabei benutzt Adobe Time Interpolation mit drei verschiedenen Optionen: Frame Sampling, Frame Blending oder Optical Flow (https://blogs.adobe.com/creativecloud/files/2015/11/OFTR_Ill_3a.png). Wenn du das hinbekommst wäre super. Ich kann dir auch eine 1-Minütige Demoaufnahme von ShadowPlay schicken, wenn dies nötig ist.

Ich habe mir noch nicht die 0.6.4 Version runtergeladen. Kann dies aber heute machen.

**Comment by Vouk** [comment]
Finally fixed in 0.7.2!
