### ISSUE TITLE
Voukoder creates variable framerate instead of constant

### ISSUE THREAD

**Issue by qo4on** [Vouk/voukoder#40]
Voukoder creates variable framerate instead of constant 60.00 fps.
![1](https://user-images.githubusercontent.com/35609308/37058196-8b983e1e-21ab-11e8-8fbe-680977039870.png)

**Comment by Vouk** [comment]
Seems like MediaInfo gets the fixed timebase from the container and premiere and ffmpeg analyze the frames.

Is the source file VFR? I am not sure how Premiere handles VFR in the exporter. I expected it to deliver CFR to an exporter.

Would you mind we move this discussion to the forum?

**Comment by qo4on** [comment]
Ok. Check the forum.

**Comment by Vouk** [comment]
Moved to: https://www.voukoder.org/forum/thread/10-voukoder-creates-variable-framerate-instead-of-constant/
