### ISSUE TITLE
Nvenc/QSV not availible as encoder

### ISSUE THREAD

**Issue by furiosarana** [Vouk/voukoder#51]
GTX 970, ffmpeg reports with ffmpeg.exe -encoders all of these hardaware accelerated options options: 
`V..... h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)`
`V..... h264_qsv             H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (Intel Quick Sync Video acceleration) (codec h264)`
`V..... nvenc                NVIDIA NVENC H.264 encoder (codec h264)`
`V..... nvenc_h264           NVIDIA NVENC H.264 encoder (codec h264)`
`V..... nvenc_hevc           NVIDIA NVENC hevc encoder (codec hevc)`
`V..... hevc_nvenc           NVIDIA NVENC hevc encoder (codec hevc)`
`V..... hevc_qsv             HEVC (Intel Quick Sync Video acceleration) (codec hevc)`
I don't know why some of these are there twice (nvenc_hevc/hevc_nvenc) and why its not an option. OBS works fine with nvenc. These are my only availible options, no matter if CUDA-Accelerationis on or off.
![unbenannt](https://user-images.githubusercontent.com/38724375/39245105-09a53808-4893-11e8-940e-fbc4b50a7ede.PNG)

**Comment by Vouk** [comment]
Please share your voukoder.log. You can find it in your %TMP% directory.
Also make sure to close all other applications using NVENC before using the voukoder.

QSV is experimental and not available yet. (And it is rather slow)

**Comment by furiosarana** [comment]
[voukoder.log](https://github.com/Vouk/voukoder/files/1947050/voukoder.log)

**Comment by Vouk** [comment]
[2018-04-25 14:10:21,386796][INFO] Nvenc initialized successfully
[2018-04-25 14:10:21,386796][INFO] 1 CUDA capable devices found
[2018-04-25 14:10:21,387803][INFO] [ GPU #0 - < GeForce GTX 970 > has Compute SM 5.2 ]
[2018-04-25 14:10:21,450799][INFO] OpenEncodeSessionEx failed: out of memory (10)
[2018-04-25 14:10:21,465303][INFO] No NVENC capable devices found
[2018-04-25 14:10:21,465303][INFO] Nvenc unloaded

Most likele all nvenc sessions are in use.

Check the NVENC related FAQs here:
https://www.voukoder.org/article/5-frequently-asked-questions-faq/

**Comment by furiosarana** [comment]
Two sessions are already in use but i cant figure out which program... Thank you anyway and in hindsight not checking the faq and just opening up a issue was being very lazy.

**Comment by Vouk** [comment]
Don't worry. I like to keep in touch with users. If you have more questions you are welcome to meet us in the forum.
